[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/editor"
  to = "/editor.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
